spring:
  profiles:
    active: dev

#server:
#  port: 9000
#spring:
#  redis:
#    database: 5
#    host: vmware.com
#    password:
#    port: 6379
#    timeout: 3000
#    jedis:
#      pool:
#        max-idle: 10
#        min-idle: 2
#        max-active: 100
#        max-wait: 3000
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://vmware.com:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia%2FShanghai
#    username: root
#    password: 123123
#    type: com.alibaba.druid.pool.DruidDataSource
#    initialSize: 5
#    minIdle: 5
#    maxActive: 20
#    maxWait: 60000
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: SELECT 1
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    filters: stat,wall,log4j
#    maxPoolPreparedStatementPerConnectionSize: 20
#    useGlobalDataSourceStat: true
#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
#ribbon:
#  ReadTimeout: 5000
#  ConnectTimeout: 5000
#  MaxAutoRetries: 1
#  MaxAutoRetriesNextServer: 1
#zuul:
#  add-host-header: true
#  sensitiveHeaders: Cookie,Set-Cookie,Authorization
#  routes:
#    admin:
#      path: /api/admin/**
#      serviceId: dora-admin
#      stripPrefix: false
